"""Demo case library for the Ambient CDS — 50 realistic outpatient encounters.

Browsable from /ambient (the case board). Each case carries the inputs the engine runs on
(transcript + patient context + mode). ILLUSTRATIVE teaching content across a distribution of age,
population, complexity, and medications — designed to exercise the engine's features end to end.
"""
from __future__ import annotations

LIBRARY = [
    {
        "id": "hfref_gdmt_gaps",
        "title": "HFrEF, three-pillar GDMT gap",
        "category": "Cardiometabolic",
        "age": 62,
        "sex": "male",
        "complexity": "Multimorbid",
        "transcript": "62-year-old man with HFrEF, EF 30%, here for follow-up. He's only on lisinopril and carvedilol; no SGLT2 inhibitor and no MRA on board.",
        "patient": {
            "egfr": 68,
            "conditions": ["HFrEF", "hypertension"],
            "current_meds": ["lisinopril", "carvedilol"],
        },
        "mode": "US",
        "demonstrates": "HFrEF GDMT gaps (missing SGLT2i + MRA pillars)",
    },
    {
        "id": "hfref_dm_sglt2",
        "title": "HFrEF + T2DM, doubly-indicated SGLT2i missing",
        "category": "Cardiometabolic",
        "age": 68,
        "sex": "male",
        "complexity": "Multimorbid",
        "transcript": "68-year-old with HFrEF and type 2 diabetes, EF 35%, on metformin, lisinopril, and metoprolol. No SGLT2 inhibitor started despite both indications.",
        "patient": {
            "egfr": 61,
            "conditions": ["HFrEF", "type 2 diabetes"],
            "current_meds": ["metformin", "lisinopril", "metoprolol"],
        },
        "mode": "US",
        "demonstrates": "Doubly-indicated SGLT2i (heart failure + diabetes)",
    },
    {
        "id": "hf_hyperkalemia_hold_mra",
        "title": "HFrEF, potassium 5.6 on RAS + MRA",
        "category": "Cardiometabolic",
        "age": 71,
        "sex": "female",
        "complexity": "Multimorbid",
        "transcript": "71-year-old woman with HFrEF on lisinopril and spironolactone; today's potassium 5.6. Was going to uptitrate but need to address the hyperkalemia first.",
        "patient": {
            "egfr": 44,
            "conditions": ["HFrEF", "hypertension"],
            "current_meds": ["lisinopril", "spironolactone", "furosemide"],
        },
        "mode": "US",
        "demonstrates": "K >=5.5 -> hold MRA/RAS; ACEi + spironolactone hyperkalemia",
    },
    {
        "id": "hf_bradycardia_hold_bb",
        "title": "HFrEF, heart rate 44 on beta-blocker",
        "category": "Cardiometabolic",
        "age": 74,
        "sex": "male",
        "complexity": "Titration/new-dx",
        "transcript": "74-year-old with HFrEF on metoprolol, feeling lightheaded; heart rate 44 today. Was planning to uptitrate the beta-blocker.",
        "patient": {
            "egfr": 58,
            "conditions": ["HFrEF"],
            "current_meds": ["metoprolol", "lisinopril", "empagliflozin"],
        },
        "mode": "US",
        "demonstrates": "Heart rate <50 -> hold/confirm beta-blocker uptitration",
    },
    {
        "id": "hf_hypotension_confirm",
        "title": "HFrEF, BP 88/54 pre-uptitration",
        "category": "Cardiometabolic",
        "age": 66,
        "sex": "female",
        "complexity": "Titration/new-dx",
        "transcript": "66-year-old woman with HFrEF, EF 28%, on sacubitril/valsartan and carvedilol; blood pressure 88/54 and a bit dizzy today. Wanted to push the doses up.",
        "patient": {
            "egfr": 55,
            "conditions": ["HFrEF"],
            "current_meds": ["sacubitril/valsartan", "carvedilol", "dapagliflozin"],
        },
        "mode": "US",
        "demonstrates": "Systolic BP <90 -> confirm beta-blocker/RAS uptitration",
    },
    {
        "id": "ckd_metformin_contra",
        "title": "T2DM, eGFR 24 on metformin",
        "category": "Renal",
        "age": 70,
        "sex": "male",
        "complexity": "Multimorbid",
        "transcript": "70-year-old with type 2 diabetes and chronic kidney disease, eGFR 24, still on metformin. Sugars run high but renal function has declined.",
        "patient": {
            "egfr": 24,
            "conditions": ["type 2 diabetes", "chronic kidney disease", "hypertension"],
            "current_meds": ["metformin", "losartan", "atorvastatin"],
        },
        "mode": "US",
        "demonstrates": "eGFR <30 -> metformin contraindicated",
    },
    {
        "id": "sglt2_egfr_low_confirm",
        "title": "CKD, eGFR 18, SGLT2 candidacy",
        "category": "Renal",
        "age": 73,
        "sex": "male",
        "complexity": "Multimorbid",
        "transcript": "73-year-old with type 2 diabetes and advanced CKD, eGFR 18. Considering starting dapagliflozin for renal protection.",
        "patient": {
            "egfr": 18,
            "conditions": ["type 2 diabetes", "chronic kidney disease"],
            "current_meds": ["insulin glargine", "losartan"],
        },
        "mode": "US",
        "demonstrates": "eGFR <20 -> confirm SGLT2 initiation",
    },
    {
        "id": "afib_anticoag_gap",
        "title": "AFib + HTN, no anticoagulation",
        "category": "Anticoagulation",
        "age": 72,
        "sex": "female",
        "complexity": "Single condition",
        "transcript": "72-year-old woman with atrial fibrillation and hypertension, on metoprolol for rate control but not on any anticoagulant.",
        "patient": {
            "egfr": 62,
            "conditions": ["atrial fibrillation", "hypertension"],
            "current_meds": ["metoprolol", "amlodipine"],
        },
        "mode": "US",
        "demonstrates": "AFib stroke-risk anticoagulation gap (age >=65 + HTN)",
    },
    {
        "id": "lone_afib_young",
        "title": "Lone AFib, young and healthy",
        "category": "Anticoagulation",
        "age": 32,
        "sex": "male",
        "complexity": "Single condition",
        "transcript": "32-year-old otherwise healthy man with lone atrial fibrillation, no hypertension, no diabetes, no heart failure. Here to discuss rate control.",
        "patient": {
            "egfr": 95,
            "conditions": ["atrial fibrillation"],
            "current_meds": ["metoprolol"],
        },
        "mode": "US",
        "demonstrates": "Lone AFib in low-risk young patient -> should NOT flag anticoagulation",
    },
    {
        "id": "postmi_statin_gap",
        "title": "Post-MI, no statin",
        "category": "Cardiometabolic",
        "age": 58,
        "sex": "male",
        "complexity": "Post-hospitalization",
        "transcript": "58-year-old man post-MI three months ago, now on aspirin and metoprolol but somehow never got started on a statin.",
        "patient": {
            "egfr": 78,
            "conditions": ["coronary artery disease", "post-MI", "hyperlipidemia"],
            "current_meds": ["aspirin", "metoprolol"],
        },
        "recent_hosp": True,
        "mode": "US",
        "demonstrates": "ASCVD/post-MI statin gap",
    },
    {
        "id": "postmi_antiplatelet_gap",
        "title": "Post-stent, no antiplatelet",
        "category": "Cardiometabolic",
        "age": 61,
        "sex": "male",
        "complexity": "Post-hospitalization",
        "transcript": "61-year-old with coronary artery disease and a recent stent, on atorvastatin but not on aspirin or clopidogrel.",
        "patient": {
            "egfr": 70,
            "conditions": ["coronary artery disease", "stent", "hypertension"],
            "current_meds": ["atorvastatin", "lisinopril"],
        },
        "recent_hosp": True,
        "mode": "US",
        "demonstrates": "ASCVD/post-stent antiplatelet gap",
    },
    {
        "id": "asthma_rescue_only",
        "title": "Asthma, rescue-only",
        "category": "Respiratory",
        "age": 24,
        "sex": "female",
        "complexity": "Single condition",
        "transcript": "24-year-old with asthma using albuterol several times a week for symptoms, no controller inhaler prescribed.",
        "patient": {
            "conditions": ["asthma"],
            "current_meds": ["albuterol"],
        },
        "mode": "US",
        "demonstrates": "Asthma rescue-only, missing controller (ICS)",
    },
    {
        "id": "copd_rescue_only",
        "title": "COPD, rescue-only smoker",
        "category": "Respiratory",
        "age": 67,
        "sex": "male",
        "complexity": "Single condition",
        "transcript": "67-year-old current smoker with COPD, breathless on exertion, relying only on albuterol with no maintenance/controller inhaler like tiotropium.",
        "patient": {
            "conditions": ["COPD", "tobacco"],
            "current_meds": ["albuterol"],
        },
        "mode": "US",
        "demonstrates": "COPD rescue-only missing maintenance inhaler; tobacco",
    },
    {
        "id": "depression_ssri_start",
        "title": "New depression, SSRI",
        "category": "Behavioral health",
        "age": 40,
        "sex": "female",
        "complexity": "Titration/new-dx",
        "transcript": "40-year-old woman with new depression, PHQ-9 elevated, discussing starting sertraline today.",
        "patient": {
            "conditions": ["depression"],
            "current_meds": [],
        },
        "mode": "US",
        "demonstrates": "Depression SSRI initiation/monitoring",
    },
    {
        "id": "osteoporosis_bisphosphonate",
        "title": "Osteoporosis, no bisphosphonate",
        "category": "Bone & endocrine",
        "age": 70,
        "sex": "female",
        "complexity": "Single condition",
        "transcript": "70-year-old woman with osteoporosis on DEXA (T-score -2.8) and a prior wrist fracture, not on any bone therapy like alendronate.",
        "patient": {
            "egfr": 66,
            "conditions": ["osteoporosis"],
            "current_meds": ["levothyroxine"],
        },
        "mode": "US",
        "demonstrates": "Osteoporosis treatment gap (bisphosphonate)",
    },
    {
        "id": "hypothyroid_tsh_monitor",
        "title": "Hypothyroidism, TSH monitoring",
        "category": "Bone & endocrine",
        "age": 55,
        "sex": "female",
        "complexity": "Routine",
        "transcript": "55-year-old woman with hypothyroidism on levothyroxine, dose changed a few months ago, here for routine follow-up.",
        "patient": {
            "conditions": ["hypothyroidism"],
            "current_meds": ["levothyroxine"],
        },
        "mode": "US",
        "demonstrates": "Hypothyroidism TSH monitoring after dose change",
    },
    {
        "id": "warfarin_nsaid",
        "title": "Warfarin + ibuprofen",
        "category": "Medication safety",
        "age": 69,
        "sex": "male",
        "complexity": "Polypharmacy",
        "transcript": "69-year-old on warfarin for atrial fibrillation, tells me he's been taking ibuprofen daily for knee pain.",
        "patient": {
            "egfr": 64,
            "conditions": ["atrial fibrillation"],
            "current_meds": ["warfarin", "ibuprofen", "metoprolol"],
        },
        "mode": "US",
        "demonstrates": "Warfarin + NSAID bleeding interaction",
    },
    {
        "id": "acei_spironolactone",
        "title": "Resistant HTN, ACEi + spironolactone",
        "category": "Medication safety",
        "age": 64,
        "sex": "male",
        "complexity": "Polypharmacy",
        "transcript": "64-year-old with resistant hypertension; adding spironolactone on top of his lisinopril today. No recent potassium on file.",
        "patient": {
            "egfr": 59,
            "conditions": ["hypertension"],
            "current_meds": ["lisinopril", "amlodipine", "spironolactone"],
        },
        "mode": "US",
        "demonstrates": "ACEi + spironolactone hyperkalemia interaction",
    },
    {
        "id": "clarithromycin_statin",
        "title": "Clarithromycin + atorvastatin",
        "category": "Medication safety",
        "age": 60,
        "sex": "female",
        "complexity": "Single condition",
        "transcript": "60-year-old on atorvastatin, being prescribed clarithromycin today for a respiratory infection.",
        "patient": {
            "conditions": ["hyperlipidemia"],
            "current_meds": ["atorvastatin", "clarithromycin"],
        },
        "mode": "US",
        "demonstrates": "Clarithromycin + atorvastatin rhabdomyolysis interaction",
    },
    {
        "id": "ssri_tramadol",
        "title": "Sertraline + tramadol",
        "category": "Medication safety",
        "age": 52,
        "sex": "female",
        "complexity": "Polypharmacy",
        "transcript": "52-year-old with depression on sertraline; wants something for back pain and has been taking tramadol.",
        "patient": {
            "conditions": ["depression"],
            "current_meds": ["sertraline", "tramadol"],
        },
        "mode": "US",
        "demonstrates": "SSRI + tramadol serotonin-syndrome interaction",
    },
    {
        "id": "doac_antiplatelet",
        "title": "Apixaban + aspirin",
        "category": "Anticoagulation",
        "age": 70,
        "sex": "male",
        "complexity": "Polypharmacy",
        "transcript": "70-year-old with atrial fibrillation on apixaban who is also taking aspirin daily without a clear indication.",
        "patient": {
            "egfr": 60,
            "conditions": ["atrial fibrillation"],
            "current_meds": ["apixaban", "aspirin", "metoprolol"],
        },
        "mode": "US",
        "demonstrates": "Anticoagulant + antiplatelet combined bleeding risk",
    },
    {
        "id": "clopidogrel_pantoprazole",
        "title": "Clopidogrel + pantoprazole",
        "category": "Medication safety",
        "age": 65,
        "sex": "male",
        "complexity": "Post-hospitalization",
        "transcript": "65-year-old post-stent on clopidogrel, started on pantoprazole for reflux.",
        "patient": {
            "egfr": 72,
            "conditions": ["coronary artery disease", "stent"],
            "current_meds": ["clopidogrel", "aspirin", "pantoprazole", "atorvastatin"],
        },
        "recent_hosp": True,
        "mode": "US",
        "demonstrates": "Clopidogrel + pantoprazole efficacy interaction",
    },
    {
        "id": "digoxin_furosemide",
        "title": "Elderly, digoxin + furosemide",
        "category": "Polypharmacy / elderly",
        "age": 82,
        "sex": "female",
        "complexity": "Polypharmacy",
        "transcript": "82-year-old woman with heart failure and atrial fibrillation on digoxin and furosemide, feeling nauseated and a little off.",
        "patient": {
            "egfr": 41,
            "conditions": ["CHF", "atrial fibrillation"],
            "current_meds": ["digoxin", "furosemide", "metoprolol", "apixaban"],
        },
        "mode": "US",
        "demonstrates": "Digoxin + furosemide (hypokalemia -> digoxin toxicity)",
    },
    {
        "id": "penicillin_allergy_amox",
        "title": "Penicillin allergy + amoxicillin",
        "category": "Medication safety",
        "age": 45,
        "sex": "female",
        "complexity": "Single condition",
        "transcript": "45-year-old with sinusitis; about to prescribe amoxicillin (Augmentin), though she has a documented penicillin allergy.",
        "patient": {
            "allergies": ["penicillin"],
            "current_meds": ["amoxicillin"],
        },
        "mode": "US",
        "demonstrates": "Drug-allergy: penicillin allergy + amoxicillin/Augmentin",
    },
    {
        "id": "peds_asthma_controller",
        "title": "Pediatric asthma, rescue-only",
        "category": "Pediatric",
        "age": 12,
        "sex": "male",
        "complexity": "Single condition",
        "transcript": "12-year-old with asthma using his albuterol inhaler almost daily and waking at night; he has no controller inhaler.",
        "patient": {
            "conditions": ["asthma"],
            "current_meds": ["albuterol"],
        },
        "mode": "US",
        "demonstrates": "Pediatric asthma rescue-only, missing controller",
    },
    {
        "id": "peds_aspirin_caution",
        "title": "Child on aspirin, viral illness",
        "category": "Pediatric",
        "age": 10,
        "sex": "female",
        "complexity": "Single condition",
        "transcript": "10-year-old with a febrile viral illness; family has been giving aspirin for the fever.",
        "patient": {
            "current_meds": ["aspirin"],
        },
        "mode": "US",
        "demonstrates": "Pediatric caution: aspirin under 16 (Reye risk)",
    },
    {
        "id": "peds_cipro_caution",
        "title": "Child prescribed ciprofloxacin",
        "category": "Pediatric",
        "age": 8,
        "sex": "male",
        "complexity": "Single condition",
        "transcript": "8-year-old with a UTI where the walk-in clinic started ciprofloxacin.",
        "patient": {
            "current_meds": ["ciprofloxacin"],
        },
        "mode": "US",
        "demonstrates": "Pediatric caution: fluoroquinolone (ciprofloxacin) in a child",
    },
    {
        "id": "preg_acei_hold",
        "title": "Pregnant, on lisinopril",
        "category": "Women's health",
        "age": 31,
        "sex": "female",
        "complexity": "Single condition",
        "transcript": "31-year-old, newly pregnant, still taking lisinopril for chronic hypertension.",
        "patient": {
            "conditions": ["hypertension"],
            "current_meds": ["lisinopril"],
            "pregnant": True,
        },
        "mode": "US",
        "demonstrates": "Pregnancy -> hold ACEi (teratogenic)",
    },
    {
        "id": "preg_statin_hold",
        "title": "Pregnant, on atorvastatin",
        "category": "Women's health",
        "age": 34,
        "sex": "female",
        "complexity": "Single condition",
        "transcript": "34-year-old, 9 weeks pregnant, on atorvastatin for hyperlipidemia; came in for prenatal med review.",
        "patient": {
            "conditions": ["hyperlipidemia"],
            "current_meds": ["atorvastatin"],
            "pregnant": True,
        },
        "mode": "US",
        "demonstrates": "Pregnancy -> hold statin",
    },
    {
        "id": "colon_screening_due",
        "title": "Routine visit, colon screening due",
        "category": "Preventive",
        "age": 52,
        "sex": "male",
        "complexity": "Routine",
        "transcript": "52-year-old here for an annual visit, feeling well, no chronic problems; has never had colon cancer screening.",
        "patient": {
            "current_meds": [],
        },
        "mode": "US",
        "demonstrates": "Age-based prevention: colon screening (45-75)",
    },
    {
        "id": "shingles_vaccine_due",
        "title": "Well visit, shingles vaccine due",
        "category": "Preventive",
        "age": 58,
        "sex": "female",
        "complexity": "Routine",
        "transcript": "58-year-old in for a wellness check, generally healthy, has not had the shingles vaccine.",
        "patient": {
            "current_meds": [],
        },
        "mode": "US",
        "demonstrates": "Age-based prevention: shingles vaccine (>=50)",
    },
    {
        "id": "pneumococcal_vaccine_due",
        "title": "Older adult, pneumococcal due",
        "category": "Preventive",
        "age": 68,
        "sex": "male",
        "complexity": "Routine",
        "transcript": "68-year-old for a routine visit, hypertension well controlled on amlodipine; no pneumococcal vaccine on record.",
        "patient": {
            "conditions": ["hypertension"],
            "current_meds": ["amlodipine"],
        },
        "mode": "US",
        "demonstrates": "Age-based prevention: pneumococcal vaccine (>=65)",
    },
    {
        "id": "well_visit_young",
        "title": "Young adult well visit",
        "category": "Preventive",
        "age": 28,
        "sex": "female",
        "complexity": "Routine",
        "transcript": "28-year-old here for a routine well visit, no chronic conditions and on no medications, feeling well.",
        "patient": {
            "current_meds": [],
        },
        "mode": "US",
        "demonstrates": "Routine well visit, low-yield prevention baseline",
    },
    {
        "id": "smoking_cessation",
        "title": "Smoker, cessation counseling",
        "category": "Preventive",
        "age": 44,
        "sex": "male",
        "complexity": "Routine",
        "transcript": "44-year-old smoker, about a pack a day for 20 years, here for a physical and interested in quitting.",
        "patient": {
            "conditions": ["tobacco"],
            "current_meds": [],
        },
        "mode": "US",
        "demonstrates": "Prevention: tobacco cessation counseling",
    },
    {
        "id": "india_glycomet_ckd",
        "title": "India: Glycomet with low eGFR",
        "category": "India",
        "age": 63,
        "sex": "male",
        "complexity": "Multimorbid",
        "transcript": "63-year-old with type 2 diabetes and chronic kidney disease, eGFR 26, still on Glycomet (metformin) prescribed locally.",
        "patient": {
            "egfr": 26,
            "conditions": ["type 2 diabetes", "chronic kidney disease"],
            "current_meds": ["Glycomet", "Storvas"],
        },
        "mode": "IN",
        "demonstrates": "India brand (Glycomet) + eGFR <30 metformin contraindication",
    },
    {
        "id": "india_aceclofenac_ckd",
        "title": "India: Hifenac in CKD",
        "category": "India",
        "age": 58,
        "sex": "male",
        "complexity": "Single condition",
        "transcript": "58-year-old with chronic kidney disease, eGFR 32, taking Hifenac (aceclofenac) daily for back pain.",
        "patient": {
            "egfr": 32,
            "conditions": ["chronic kidney disease", "hypertension"],
            "current_meds": ["Hifenac", "Cardace"],
        },
        "mode": "IN",
        "demonstrates": "India: NSAID (aceclofenac) in CKD nephrotoxicity",
    },
    {
        "id": "india_warf_nsaid",
        "title": "India: Warf + Hifenac",
        "category": "India",
        "age": 66,
        "sex": "female",
        "complexity": "Polypharmacy",
        "transcript": "66-year-old on Warf (warfarin) for atrial fibrillation, also taking Hifenac (aceclofenac) she bought over the counter for arthritis.",
        "patient": {
            "egfr": 57,
            "conditions": ["atrial fibrillation"],
            "current_meds": ["Warf", "Hifenac", "Ecosprin"],
        },
        "mode": "IN",
        "demonstrates": "India: warfarin brand + NSAID bleeding; plus anticoag + aspirin",
    },
    {
        "id": "india_banned_fdc",
        "title": "India: banned FDC analgesic",
        "category": "India",
        "age": 49,
        "sex": "male",
        "complexity": "Single condition",
        "transcript": "49-year-old bought an over-the-counter fixed-dose combination pain tablet of aceclofenac plus a muscle relaxant that is on the banned-FDC list, using it daily for neck pain.",
        "patient": {
            "conditions": ["hypertension"],
            "current_meds": ["aceclofenac", "Cardace"],
        },
        "mode": "IN",
        "demonstrates": "India: banned fixed-dose combination scenario",
    },
    {
        "id": "india_postmi_ecosprin_storvas",
        "title": "India: post-MI, statin gap",
        "category": "India",
        "age": 60,
        "sex": "male",
        "complexity": "Post-hospitalization",
        "transcript": "60-year-old post-MI last month, discharged on Ecosprin (aspirin) but no statin; his cholesterol was high on discharge.",
        "patient": {
            "egfr": 74,
            "conditions": ["coronary artery disease", "post-MI", "hyperlipidemia"],
            "current_meds": ["Ecosprin"],
        },
        "recent_hosp": True,
        "mode": "IN",
        "demonstrates": "India: post-MI statin gap (Storvas not started)",
    },
    {
        "id": "india_pan_clopidogrel",
        "title": "India: Pan + clopidogrel",
        "category": "India",
        "age": 64,
        "sex": "male",
        "complexity": "Polypharmacy",
        "transcript": "64-year-old with coronary artery disease on clopidogrel and Ecosprin, started on Pan (pantoprazole) for gastritis.",
        "patient": {
            "egfr": 69,
            "conditions": ["coronary artery disease"],
            "current_meds": ["clopidogrel", "Ecosprin", "Pan", "Storvas"],
        },
        "mode": "IN",
        "demonstrates": "India: clopidogrel + pantoprazole (Pan) efficacy interaction",
    },
    {
        "id": "negation_no_diabetes",
        "title": "Negation: 'no diabetes'",
        "category": "Cardiometabolic",
        "age": 47,
        "sex": "male",
        "complexity": "Routine",
        "transcript": "47-year-old with hypertension on amlodipine here for follow-up; no diabetes and A1c was normal last year.",
        "patient": {
            "conditions": ["hypertension"],
            "current_meds": ["amlodipine"],
        },
        "mode": "US",
        "demonstrates": "Negation robustness: 'no diabetes' must not trigger diabetes logic",
    },
    {
        "id": "negation_quit_smoking",
        "title": "Negation: quit smoking years ago",
        "category": "Preventive",
        "age": 55,
        "sex": "male",
        "complexity": "Routine",
        "transcript": "55-year-old for an annual visit; he quit smoking years ago and has no active tobacco use now.",
        "patient": {
            "current_meds": [],
        },
        "mode": "US",
        "demonstrates": "Negation robustness: former smoker must not flag as active tobacco",
    },
    {
        "id": "negation_stopped_lisinopril",
        "title": "Negation: stopped lisinopril",
        "category": "Cardiometabolic",
        "age": 59,
        "sex": "female",
        "complexity": "Single condition",
        "transcript": "59-year-old with hypertension who stopped her lisinopril two months ago due to cough; now only on amlodipine.",
        "patient": {
            "conditions": ["hypertension"],
            "current_meds": ["amlodipine"],
        },
        "mode": "US",
        "demonstrates": "Negation robustness: discontinued lisinopril not counted as current",
    },
    {
        "id": "coverage_gap_missing_egfr",
        "title": "SGLT2 candidate, eGFR unavailable",
        "category": "Renal",
        "age": 69,
        "sex": "male",
        "complexity": "Multimorbid",
        "transcript": "69-year-old with HFrEF and type 2 diabetes on metformin and lisinopril; strong SGLT2 inhibitor candidate but no recent eGFR is available.",
        "patient": {
            "conditions": ["HFrEF", "type 2 diabetes"],
            "current_meds": ["metformin", "lisinopril"],
        },
        "mode": "US",
        "demonstrates": "Honest coverage gap: eGFR missing -> cannot verify renal safety",
    },
    {
        "id": "elderly_polypharmacy_multimorbid",
        "title": "85yo, multimorbid polypharmacy",
        "category": "Polypharmacy / elderly",
        "age": 85,
        "sex": "male",
        "complexity": "Polypharmacy",
        "transcript": "85-year-old with HFrEF, type 2 diabetes, atrial fibrillation, and CKD on metoprolol, furosemide, apixaban, insulin glargine, and atorvastatin; here for a med review.",
        "patient": {
            "egfr": 38,
            "conditions": ["HFrEF", "type 2 diabetes", "atrial fibrillation", "chronic kidney disease"],
            "current_meds": ["metoprolol", "furosemide", "apixaban", "insulin glargine", "atorvastatin"],
        },
        "mode": "US",
        "demonstrates": "Elderly polypharmacy reconciliation + HF/SGLT2 opportunity",
    },
    {
        "id": "elderly_falls_polypharmacy",
        "title": "88yo, falls and gabapentin",
        "category": "Polypharmacy / elderly",
        "age": 88,
        "sex": "female",
        "complexity": "Polypharmacy",
        "transcript": "88-year-old woman with recent falls, on gabapentin and tramadol for neuropathy plus sertraline for depression; feeling drowsy and unsteady.",
        "patient": {
            "egfr": 43,
            "conditions": ["depression"],
            "current_meds": ["gabapentin", "tramadol", "sertraline", "amlodipine"],
        },
        "mode": "US",
        "demonstrates": "Elderly falls risk / sedation burden; SSRI + tramadol serotonin risk",
    },
    {
        "id": "elderly_ckd_polypharmacy",
        "title": "80yo, CKD + NSAID + RAS",
        "category": "Polypharmacy / elderly",
        "age": 80,
        "sex": "male",
        "complexity": "Polypharmacy",
        "transcript": "80-year-old with chronic kidney disease, eGFR 29 and potassium 5.6, on losartan and taking naproxen for arthritis.",
        "patient": {
            "egfr": 29,
            "conditions": ["chronic kidney disease", "hypertension"],
            "current_meds": ["losartan", "naproxen", "atorvastatin"],
        },
        "mode": "US",
        "demonstrates": "Elderly CKD: NSAID nephrotoxicity + K >=5.5 with RAS blockade",
    },
    {
        "id": "elderly_afib_multimorbid",
        "title": "84yo AFib, anticoag review",
        "category": "Polypharmacy / elderly",
        "age": 84,
        "sex": "female",
        "complexity": "Multimorbid",
        "transcript": "84-year-old woman with atrial fibrillation, hypertension, and type 2 diabetes on metoprolol and amlodipine, not on any anticoagulant.",
        "patient": {
            "egfr": 52,
            "conditions": ["atrial fibrillation", "hypertension", "type 2 diabetes"],
            "current_meds": ["metoprolol", "amlodipine", "metformin"],
        },
        "mode": "US",
        "demonstrates": "Elderly high-risk AFib anticoagulation gap",
    },
    {
        "id": "elderly_hf_multimorbid",
        "title": "79yo HFrEF, K 5.6 + SBP low",
        "category": "Polypharmacy / elderly",
        "age": 79,
        "sex": "male",
        "complexity": "Multimorbid",
        "transcript": "79-year-old with HFrEF, EF 30%, on lisinopril, carvedilol, spironolactone, and furosemide; today potassium 5.6 and blood pressure 88/56.",
        "patient": {
            "egfr": 40,
            "conditions": ["HFrEF", "hypertension"],
            "current_meds": ["lisinopril", "carvedilol", "spironolactone", "furosemide"],
        },
        "mode": "US",
        "demonstrates": "Elderly HFrEF: hyperkalemia hold + hypotension confirm together",
    },
    {
        "id": "ascvd_primary_statin_gap",
        "title": "High ASCVD risk, no statin",
        "category": "Cardiometabolic",
        "age": 56,
        "sex": "male",
        "complexity": "Single condition",
        "transcript": "56-year-old with type 2 diabetes, hypertension, and high cholesterol, A1c 9.1, on metformin and lisinopril but not on a statin.",
        "patient": {
            "egfr": 76,
            "conditions": ["type 2 diabetes", "hypertension", "hyperlipidemia"],
            "current_meds": ["metformin", "lisinopril"],
        },
        "mode": "US",
        "demonstrates": "ASCVD primary-prevention statin gap in diabetes",
    },
]


# --- Illustrative patient identity (synthetic, deterministic per case) ---------------------------
# Demo-only demographics so the encounter reads like a real note. NOT real patient data.
import datetime as _dt
import hashlib as _hl

_FIRST_M = ["James", "Robert", "David", "Michael", "William", "Thomas", "Raj", "Wei", "Omar", "Luis",
            "Henry", "George", "Samuel", "Arjun", "Daniel", "Frank", "Peter", "Carl"]
_FIRST_F = ["Mary", "Patricia", "Linda", "Barbara", "Susan", "Margaret", "Priya", "Mei", "Fatima", "Sofia",
            "Alice", "Helen", "Ruth", "Ananya", "Grace", "Nora", "Clara", "Rosa"]
_LAST = ["Anderson", "Miller", "Garcia", "Nguyen", "Patel", "Kim", "Johnson", "Brown", "Okafor", "Rossi",
         "Silva", "Ivanov", "Sharma", "Cohen", "Hansen", "Mbeki", "Olsen", "Reyes"]
_CITY = ["Springfield, IL", "Aurora, CO", "Fresno, CA", "Dayton, OH", "Tacoma, WA", "Akron, OH",
         "Mumbai, MH", "Pune, MH", "Bengaluru, KA", "Jaipur, RJ", "Kochi, KL", "Nagpur, MH"]
_DOCS = ["Dr. A. Rao", "Dr. M. Chen", "Dr. S. Patel", "Dr. J. Okafor", "Dr. L. Nguyen", "Dr. R. Kapoor",
         "Dr. E. Martinez", "Dr. K. Sharma", "Dr. T. Ibrahim", "Dr. P. Andersson"]


def _seed(s: str) -> int:
    return int(_hl.md5(s.encode()).hexdigest(), 16)


def enrich(case: dict) -> dict:
    """Return the case with illustrative identity fields (name, location, mrn, doctor, date) plus the
    detected conditions + primary condition, so the UI can link similar cases as clickable precedents."""
    h = _seed(case["id"])
    firsts = _FIRST_F if case.get("sex") == "female" else _FIRST_M
    # India cases draw locations from the Indian city slice
    cities = _CITY[6:] if case.get("mode") == "IN" else _CITY[:6]
    out = dict(case)
    out["name"] = f"{firsts[h % len(firsts)]} {_LAST[(h // 7) % len(_LAST)]}"
    out["location"] = cities[(h // 13) % len(cities)]
    out["mrn"] = f"MRN-{(h % 900000) + 100000}"
    out["doctor"] = _DOCS[(h // 17) % len(_DOCS)]
    out["date"] = _dt.date.today().isoformat()
    # tag conditions/primary (keyword extraction — cheap, deterministic) for precedent matching
    try:
        from .engine import extract_conditions, _PRIMARY_ORDER
        chart = [c.lower() for c in case.get("patient", {}).get("conditions", [])]
        active = [c["condition"] for c in extract_conditions(case.get("transcript", ""), chart)]
        out["conditions"] = active
        out["primary"] = next((c for c in _PRIMARY_ORDER if c in active), (active[0] if active else None))
    except Exception:
        out["conditions"] = []
        out["primary"] = None
    return out


def library() -> list:
    return [enrich(c) for c in LIBRARY]
